from __future__ import annotations

import importlib
import sys
from pathlib import Path
import inspect
import textwrap
from abc import ABC, abstractmethod 
from dataclasses import dataclass
from enum import IntEnum    
from copy import copy
from scipy.optimize import approx_fprime
from datetime import datetime
from matplotlib import pyplot as plt
import logging

logger = logging.getLogger(__name__)

import numpy as np
from numba import njit, prange
from numba.typed import List
from numba.types import UniTuple
import numba
from typing import Callable, Optional, TYPE_CHECKING, Type
import ast
from collections import namedtuple

from .matmul_map import create_optimisable_compute_flow, matmul_get_name, write_fun
from .matmul_map import SPARSITY_PROBE_SAMPLES, SPARSITY_PROBE_SEED

Import = namedtuple("Import", ["module", "name", "alias"])

def get_imports(path):
    with open(path, encoding="utf-8") as fh:
       root = ast.parse(fh.read(), path)

    for node in ast.iter_child_nodes(root):
        if isinstance(node, ast.Import):
            module = ()
        elif isinstance(node, ast.ImportFrom):  
            module = (node.module,)
        else:
            continue
        for n in node.names:
            yield Import(module, (n.name,), n.asname)

def _emit_imports(*import_sets) -> list[str]:
    """
    The import block a generated template opens with.

    Sorted, because the sources are sets: their iteration order changes with
    PYTHONHASHSEED, so an unsorted block made the emitted file reproducible
    only within one process.

    :param import_sets: the import records the blocks declared
    :return: source lines, ending in a blank one
    """
    lines = set()
    for imports in import_sets:
        for record in imports:
            alias = f" as {record.alias}" if record.alias is not None else ""
            lines.add(f"import {record.name[0]}{alias}" if len(record.module) == 0
                      else f"from {record.module[0]} import {record.name[0]}{alias}")
    return sorted(lines) + ["\n"]


def _generated_header() -> str:
    """The line that says a template is generated, and from what."""
    return (f"#generated by pyCamSet: sparsity probe seed={SPARSITY_PROBE_SEED} "
            f"samples={SPARSITY_PROBE_SAMPLES}. Deterministic -- "
            f"regenerating must reproduce this file byte for byte.")



# The body of the per detection loop, which is where the generated block calls
_INNER_LOOP_INDENT = " " * 16

_LOSS_TEMPLATE = '''\
from numba import prange, int64
from datetime import datetime
from pyCamSet.optimisation.abstract_function_blocks import make_param_struct
 
def make_full_loss(op_fun, detections, threads):
    op_fun._prep_for_computation()
    {header}
    @njit(parallel=True, fastmath=True, cache=True)
    def full_loss(inp_params, d_data, block_param_inds, n_lines, inp_mem, out_mem, wrk_mem, param_len, n_threads, d_shape, param_slices, n_outs, template = None):
        use_template = template is not None
        t_data: np.ndarray = template if use_template else np.zeros((3,1))
        losses = np.empty((n_threads, n_lines, 2))
        for i in prange(n_threads):
            #make the memory components required
            inp = np.empty(inp_mem)
            output = np.empty(out_mem)
            memory = np.empty(wrk_mem)
            dense_param_arr = np.empty(param_len)
            local_params = inp_params[block_param_inds[i].flatten()].reshape((int64(n_lines), int64(param_len)))
            for ii in range(n_lines):
                datum = d_data[i, ii]
                dense_param_arr[:] = local_params[ii]
                if use_template:
                    inp[:3] = t_data[int(datum[2])] 
{calc}
                losses[i, ii] = [output[0] - datum[3], output[1] - datum[4]]
        return np.resize(losses, (d_shape, 2))
    return full_loss'''

# n_blocks is emitted although nothing reads it. Removing it, and with it the
# only use of the n_params argument, makes numba's parfor prelowering emit
# illegal IR (a del of static_slice_size) for the rigidTform3d chains; the
# self-calibration tests are what catch it.
_JAC_TEMPLATE = '''\
from numba import prange, int64
from numba.types import int_
import scipy
from datetime import datetime
from pyCamSet.optimisation.abstract_function_blocks import make_param_struct
 
from .{matflow_module} import matflow
 
def make_full_jac(op_fun, detections, threads):
    {header}
    @njit(parallel=True,fastmath=True,cache=True)
    def full_jac(inp_params, d_data, block_param_inds, n_lines, inp_mem, wrk_mem, param_len, n_threads, param_slices, n_outs, f_outs, n_params, template = None):
        use_template = template is not None
        t_data: np.ndarray = template if use_template else np.zeros((3,1))
        n_blocks = len(n_params)
        dense_output = np.empty((n_threads, n_lines * f_outs, param_len))
        for i in prange(n_threads):
            #make the memory components required
            inp = np.empty(inp_mem)
            memory = np.empty(wrk_mem)
            dense_param_arr = np.empty(param_len)
            local_params = inp_params[block_param_inds[i].flatten()].reshape((n_lines, param_len))
            output_block = np.empty({output_block_size})
            fun_output = np.empty(np.max(n_outs))
            for ii in range(n_lines):
                datum = d_data[i, ii]
                dense_param_arr[:] = local_params[ii]
                if use_template:
                    inp[:3] = t_data[int(datum[2])] 
{calc}
                write_data = dense_output[i, f_outs*ii:f_outs*(ii+1), :]
                matflow(output_block, write_data)
        return dense_output.ravel()
    return full_jac'''


def _emit_block_calls(groups) -> str:
    """
    The per block computation lines, indented into a template's inner loop.

    :param groups: per block, the sections of source that block contributes
    :return: the lines as one indented block of source
    """
    lines = [line for group in groups for section in group for line in section]
    return textwrap.indent("\n".join(lines), _INNER_LOOP_INDENT, lambda _: True)


def _import_generated(module_name: str, freshly_written: bool):
    """
    Import a generated template, reloading it if it was just rewritten.

    ``importlib.import_module`` returns whatever is already in ``sys.modules``,
    so regenerating a template inside a running process used to hand back the
    previously compiled kernel: the new source sat on disk unused until the
    next interpreter. Any module the template imports (the matflow helper) has
    to be reloaded first, or the reloaded template would re-bind the stale one.

    :param module_name: dotted name of the generated module
    :param freshly_written: whether its source was just rewritten
    """
    importlib.invalidate_caches()
    module = sys.modules.get(module_name)
    if module is None:
        return importlib.import_module(module_name)
    if not freshly_written:
        return module
    # Drop the matflow helpers rather than reloading them: their source may
    # have been deleted or regenerated, and the template's own import will pull
    # in whatever is on disk once it re-executes.
    package = module_name.rsplit(".", 1)[0]
    for name in [n for n in sys.modules if n.startswith(package + ".matflow_")]:
        sys.modules.pop(name, None)
    try:
        return importlib.reload(module)
    except (ModuleNotFoundError, FileNotFoundError, ImportError):
        sys.modules.pop(module_name, None)
        return importlib.import_module(module_name)


class key_type(IntEnum):
    PER_CAM = 0
    PER_IMG = 1
    PER_KEY = 2
    SINGLE  = 3

@dataclass
class param_type:
    def __init__(self, link_type:key_type, n_params:int, mod_function=None) -> None:
        self.link_type = link_type
        self.n_params = n_params
        self.sparse_param = False # used to implement ordering for schops decomp

        if mod_function is None:
            self.mod_function = njit(lambda x: x)
        else:
            self.mod_function = mod_function

    def __key(self):
        return (int(self.link_type), self.n_params, self.sparse_param) 
    def __hash__(self):
        key = self.__key 
        return hash((key))

    def __eq__(self, other):
        return self.__key == other.__key

def find_first_non(stri, char):
    return next((i for i, c in enumerate(stri) if c != char), -1)

def clean_fn_data(fn):
    lbl = fn.split("\n")
    if lbl[0][0] == " ":
        #find the first non " " object
        i_level = find_first_non(lbl[0], " ")
        token_type = " "
    elif lbl[0][0] == "\t":
        #find the first non "\t" object
        i_level = find_first_non(lbl[0], "\t")
        token_type = "\t"
    else:
        raise ValueError
    #gives the indent level
    output = []
    text_indent = -1
    for l in lbl: 
        l_text = l[i_level:]
        if len(l_text) == 0:
            continue
        if l_text[0] != token_type:
            continue
        if text_indent == -1:
            poss_score = find_first_non(l_text, token_type)
            if poss_score == -1:
                continue
            text_indent = poss_score
        clean_string = l[(i_level + text_indent):]
        if token_type == " ":
            clean_string.replace(" "*text_indent, "\t")
        if not clean_string[:6] == "return":
            output.append(clean_string)
    return output



class optimisation_function:
    def __init__(self, function_blocks: list[Type[abstract_function_block]]) -> None:
    
        self.function_blocks = function_blocks
        self.n_blocks = len(function_blocks)

        self.loss_jac = None
        self.loss_fun = None

        #required working memory:
        self.working_memories = [b.array_memory for b in function_blocks]
        self.wrk_mem_req = max(self.working_memories)

        #required output_memory:
        self.grad_outputsize = [(b.num_inp + b.params.n_params) * b.num_out for b in function_blocks]

        self.out_mem_req = max(
            max(self.grad_outputsize),
            max([b.num_out for b in function_blocks]) #uses the same memory to store outpute 
            )
        self.inp_mem_req = max([b.num_inp for b in function_blocks])
        self.param_slices: np.ndarray
        self.param_line_length = None

        self.templated = function_blocks[-1].template

        self.ready_to_compute = False

        self.num_input_params = None

    def _prep_for_computation(self):
        if self.ready_to_compute:
            return
        # create numba compatible containers of functions

        self.ftemplate = numba.types.FunctionType(
            numba.void(
                numba.types.Array(numba.float64, 1, "C"),
                numba.types.Array(numba.float64, 1, "C"),
                numba.types.Array(numba.float64, 1, "C"),
                numba.types.Array(numba.float64, 1, "C"),
            )
        )

        # point locations within the jacobean matrix that will be used
        self.unique_link_inds = []
        for fb in self.function_blocks:
            if not fb.params in self.unique_link_inds:
                self.unique_link_inds.append(fb.params)
        self.block_param_inds = [self.unique_link_inds.index(fb.params) for fb in self.function_blocks]

        self.param_starts = np.cumsum([0] + [b.n_params for b in self.unique_link_inds])
        self.n_outs = np.array([b.num_out for b in self.function_blocks])
        self.n_inps = np.array([b.num_inp for b in self.function_blocks])
        self.n_params = np.array([b.params.n_params for b in self.function_blocks])

        slice = []                       
        for idb, block in enumerate(self.function_blocks):
            b_ind = self.block_param_inds[idb]
            slice.append(self.param_starts[b_ind]) 
            slice.append(self.param_starts[b_ind + 1]) 


        self.param_line_length = self.param_starts[-1] #the length of the params passed in is the last of the param starts vector.

        #so we get the number of params: with a buffer for the first function
        inp_buffer = np.cumsum([0] + [b.num_out for b in  self.function_blocks] + [0])      
        for i in range(len(self.function_blocks) + 1):
            slice.append(inp_buffer[i]  + self.param_line_length) 
            slice.append(inp_buffer[i + 1] + self.param_line_length) 
        
        self.param_slices = np.array(slice)
        self.ready_to_compute = True

    def get_block_param_inds(self, detections, threads, max_keys, max_imgs, max_cams, unthreaded=False) -> np.ndarray:
        """
        takes the detected data, and threads, then produces an array containing the inds of the relevant params.
        this array is dynamically sized to use the smallest int representation to compress the data as much as possible.

        this array defines the locations of the points given the full param structure.
        :params detections: the detection data to use for the reconstruction.
        :params threads: the number of threads that will be used.
        """
        
        n_points = detections.shape[0]
        param_num = np.sum(self.n_params)
        block_params = np.empty((n_points, param_num))

        param_slices, n_outs, working_memories, n_blocks = self._get_function_constants()
        starts, block_n_params, param_inds, key_type, num_inputs = make_param_struct(self.function_blocks, detections, 
            max_imgs=max_imgs, max_keys=max_keys, max_cams=max_cams
        )

        param_len = num_inputs

        for idp in range(n_points):
            datum = detections[idp]
            for idb in range(n_blocks):
                s_num = datum[key_type[idb]] #the index value of the associated parameter",
                p_ind = param_inds[idb] # maps the param to it's index in the unique params",
                start = starts[p_ind] + s_num * block_n_params[p_ind] #and the associated change in the start location",
                block_params[idp, param_slices[2*idb]:param_slices[2*idb + 1]] = np.arange(int(start),int(start + block_n_params[p_ind]))
        
        d_shape = block_params.shape
        p_shape = (threads, int(np.ceil(d_shape[0]/threads)), *d_shape[1:])
        data_type = 'uint32'
        if param_len < 2**16:
            data_type = 'uint16'
        if param_len < 2**8:
            data_type = 'uint8'

        if not unthreaded:
            block_params_thread = np.resize(block_params, p_shape).astype(data_type)
        else:
            block_params_thread = block_params.astype(data_type)

        return block_params_thread

    def _get_function_constants(self) -> tuple[np.ndarray,np.ndarray,np.ndarray, int]:
        return self.param_slices, self.n_outs, np.array(self.working_memories), self.n_blocks


    def _get_loss_function_components(self) -> tuple[set[Import],list[str]]:
        self._prep_for_computation()

        n_blocks = self.n_blocks

        import_set = set()

        for block in self.function_blocks[::-1]:
            base =  inspect.unwrap(block.compute_fun)
            base_code = inspect.getsource(base)
            base_code = inspect.getsourcefile(base)
            for imp in get_imports(base_code):
                import_set.add(imp)


        fn_content = []
        for i in range(n_blocks-1, -1, -1):
            prep = [ 
                f"params = dense_param_arr[param_slices[2*{i}]:param_slices[2*{i} + 1]]",
            ]
            base =  inspect.unwrap(self.function_blocks[i].compute_fun)
            base_code = inspect.getsource(base)
            section = clean_fn_data(base_code)
            end = f"inp[:n_outs[{i}]] = output[:n_outs[{i}]]"
            fn_content.append([prep, section, [end]])
        return import_set, fn_content

    def get_constants(self, detections, threads):
        """
        Returns constants about the optimisations.
        """
        starts, block_n_params, param_inds, key_type, _ = make_param_struct(self.function_blocks, detections)
        inp_mem = self.inp_mem_req
        out_mem = self.out_mem_req
        wrk_mem = self.wrk_mem_req
        param_len = np.sum(block_n_params)
        n_lines  = int(np.ceil(detections.shape[0]/threads))
        return starts, block_n_params, param_inds, key_type, inp_mem, out_mem, wrk_mem, param_len, n_lines

    def _reshape_data_for_parallel(self, detections, threads):
        """
        Resizes the detection data to have dimensions that can be evenly shifted between threads.
        """
        d_shape = detections.shape
        p_shape = (threads, int(np.ceil(d_shape[0]/threads)), *d_shape[1:])
        detection_data = np.resize(detections, p_shape)
        return detection_data

    def make_full_loss_template(self, detections, threads, problem_max_vals, overwrite_function = False) -> Callable:
        """
        Write, import and bind the loss kernel for this combination of blocks.

        The kernel is written only when it is not already on disk, so a checked
        in template is used in preference to regenerating it.

        :param detections: the detections the loss is evaluated over
        :param threads: the number of threads the kernel parallelises across
        :param problem_max_vals: the maximum camera, image and key counts
        :param overwrite_function: rewrite the template even if it exists
        :return: the loss, as a function of the parameter vector
        """
        strings = "loss_" + "_".join([str(name.__class__.__name__) for name in self.function_blocks])
        write_file = Path(__file__).parent / "template_functions" / (strings + ".py")
        module_name = "pyCamSet.optimisation.template_functions." + strings

        freshly_written = overwrite_function or not write_file.exists()
        if freshly_written:
            needed_import_set, content = self._get_loss_function_components()
            source = "\n".join(_emit_imports(needed_import_set) + [
                _LOSS_TEMPLATE.format(header=_generated_header(),
                                      calc=_emit_block_calls(content))])
            with open(write_file, 'w', encoding="utf-8", newline="\n") as f:
                f.write(source)
            self._prep_for_computation()

        top_module = _import_generated(module_name, freshly_written)
        base_loss_fn: Callable = top_module.make_full_loss(self, detections, threads)

        _,_, _,_, inp_mem, out_mem, wrk_mem, param_len, n_lines = self.get_constants(detections, threads)
        param_slices, n_outs, _, _ = self._get_function_constants()
        parallel_data = self._reshape_data_for_parallel(detections, threads)
        block_param_inds = self.get_block_param_inds(detections, threads, **problem_max_vals)
        d_shape = detections.shape[0]

        return lambda param, template=None: base_loss_fn(
            param, parallel_data, block_param_inds, n_lines,
            inp_mem, out_mem, wrk_mem, param_len, threads, d_shape,
            param_slices, n_outs,
            template=template
        )

    def _get_jac_constants(self):
        return self.param_slices, self.n_outs, np

    def _get_loss_jac_strings(self):
        self._prep_for_computation()

        n_blocks = self.n_blocks

        import_set = set()

        for block in self.function_blocks[::-1]:
            base =  inspect.unwrap(block.compute_jac)
            base_code = inspect.getsource(base)
            base_code = inspect.getsourcefile(base)
            for imp in get_imports(base_code):
                import_set.add(imp)

        #calculate the offsets

        out_sizes = [0]
        for element in self.function_blocks:
            elem_outsize = (element.params.n_params + element.num_inp) * element.num_out
            out_sizes.append(elem_outsize)
        block_slices = np.cumsum(out_sizes) #this is actually quite a large array, but still kind of small
        fn_content = []
        for i in range(n_blocks-1, -1, -1):
            prep = [ 
                f"################# BLOCK {i} #################",
                f"params = dense_param_arr[param_slices[2*{i}]:param_slices[2*{i}+1]]",
                f"#could set the outputs vector here",
                f"output = output_block[{block_slices[i]}:{block_slices[i+1]}]"
            ]
            base =  inspect.unwrap(self.function_blocks[i].compute_jac)
            base_code = inspect.getsource(base)
            section = clean_fn_data(base_code)
            end = [ #replace this with an inlined function?
                f"################## normal function eval",
                f"output = fun_output[:n_outs[{i}]]"
            ] #end now has no elements.
            fn_content.append([prep, section, end])


        return import_set, fn_content

    def make_jac_CSR_columns_row_pointers(self, detections, threads, unfixed_params, problem_maximums):
        """
        Takes the detected data, and then returns the CSR representation of the matrix.
        If some params are indicated as fixed, the indicies of those params are removed from the output.

        This modifies the locations of the effective columns of the data.
        """
        _, _, _, _, _, _, _, param_len, _ = self.get_constants(detections, threads)
        c = np.repeat(
            np.resize(self.get_block_param_inds(detections, threads, **problem_maximums), (detections.shape[0], param_len)),
            2, axis=0
        
        )
        #map the values of c to their equiv index in the input params.
        #values that are blanked will duplicate, then remove.
        conversion =  np.concatenate([[0], np.cumsum(unfixed_params)], axis=0)
        param_mask = unfixed_params[c] #this is a boolean mask containing if points should be removed.
        c = conversion[c]
        valid_c = c[param_mask] #valid_c has no array structure and is a single line

        proto_compressed_rows = np.cumsum(np.sum(param_mask, axis=1))
        compressed_rows = np.concatenate([[0], proto_compressed_rows])
        return valid_c, compressed_rows 


    def make_full_jac_template(self, detections, threads, unfixed_params, problem_max_vals, overwrite_function=False, return_blocks=False) -> Callable:
        """
        Write, import and bind the jacobian kernel for this combination of blocks.

        :param detections: the detections the jacobian is evaluated over
        :param threads: the number of threads the kernel parallelises across
        :param unfixed_params: mask of the parameters the solve may move
        :param problem_max_vals: the maximum camera, image and key counts
        :param overwrite_function: rewrite the template even if it exists
        :param return_blocks: give the per residual blocks rather than a CSR
        :return: the jacobian, as a function of the parameter vector
        """
        mat_scriptname = matmul_get_name(self)
        matmul_loc = Path(__file__).parent / "template_functions" / (mat_scriptname + ".py")
        if not matmul_loc.exists() or overwrite_function:
            logger.warning("Compiling the matrix flow for this calibration.")
            lines = create_optimisable_compute_flow(self, in_name="output_block", out_name="write_data")
            write_fun(self, lines, input_name="output_block", output_name="write_data")

        strings = "jac_" + "_".join([str(name.__class__.__name__) for name in self.function_blocks])
        write_file = Path(__file__).parent / "template_functions" / (strings + ".py")
        module_name = "pyCamSet.optimisation.template_functions." + strings

        freshly_written = overwrite_function or not write_file.exists()
        if freshly_written:
            logger.warning(f"Compiling the jacobian definition for the {strings} calibration")
            needed_import_set, content = self._get_loss_function_components()
            jac_needed_imports_set, jac_content = self._get_loss_jac_strings()

            out_sizes = [0] + [(block.params.n_params + block.num_inp) * block.num_out
                               for block in self.function_blocks]
            output_block_size = np.cumsum(out_sizes)[-1]

            # Each block's jacobian, then the block itself, so every derivative
            # is taken at the inputs its block was evaluated on. The final
            # block's forward section is dropped: nothing reads its output.
            interleaved = [part for pair in zip(jac_content, content) for part in pair]

            source = "\n".join(_emit_imports(needed_import_set, jac_needed_imports_set) + [
                _JAC_TEMPLATE.format(matflow_module=mat_scriptname,
                                     header=_generated_header(),
                                     output_block_size=output_block_size,
                                     calc=_emit_block_calls(interleaved[:-1]))])
            with open(write_file, 'w', encoding="utf-8", newline="\n") as f:
                f.write(source + "\n")

        top_module = _import_generated(module_name, freshly_written)
        base_jac_fn: Callable = top_module.make_full_jac(self, detections, threads)

        _,_, _,_, inp_mem, _, wrk_mem, param_len, n_lines = self.get_constants(detections, threads)
        param_slices, n_outs, _, _ = self._get_function_constants()
        parallel_data = self._reshape_data_for_parallel(detections, threads)
        block_param_inds = self.get_block_param_inds(detections, threads, **problem_max_vals)
        block_param_inds_unthreaded = self.get_block_param_inds(detections, threads, unthreaded=True, **problem_max_vals)
        c, compressed_row = self.make_jac_CSR_columns_row_pointers(detections, threads, unfixed_params, problem_maximums=problem_max_vals)
        n_params = np.array(self.n_params)
        f_outs = 2

        jac_param_inds = np.repeat(block_param_inds_unthreaded, 2, axis=0)
        good_mask = unfixed_params[jac_param_inds].flatten()
        output_shape = jac_param_inds.shape
        n_elements = np.prod(output_shape)

        def evaluate(param, template):
            return base_jac_fn(
                param, parallel_data, block_param_inds, n_lines,
                inp_mem, wrk_mem, param_len, threads,
                param_slices, n_outs, f_outs, n_params,
                template=template
            )[:n_elements]

        if return_blocks:
            def block_fn(param, template=None):
                return evaluate(param, template).reshape(output_shape)
            return block_fn

        if np.all(unfixed_params):
            def jac_fn(param, template=None):
                return evaluate(param, template), c, compressed_row
            return jac_fn

        def jac_fn(param, template=None):
            return evaluate(param, template)[good_mask], c, compressed_row
        return jac_fn

    
    def make_full_loss_fn(self, detections, threads, problem_maximums=None):
        if problem_maximums is None:
            problem_maximums = {"max_cams": None , "max_imgs": None, "max_keys": None}
        self._prep_for_computation()
        return self.make_full_loss_template(detections, threads, problem_max_vals=problem_maximums)

    def make_jacobean(self, detections, threads, unfixed_params=None, problem_maximums=None,
                      return_blocks=False):
        if problem_maximums is None:
            problem_maximums = {"max_cams": None , "max_imgs": None, "max_keys": None}
        _, _, _, _, num_inps = make_param_struct(self.function_blocks, detections, **problem_maximums)
        if unfixed_params is None:
            unfixed_params = np.ones(num_inps, dtype=bool)
        self._prep_for_computation()
        func = self.make_full_jac_template(detections, threads, unfixed_params,
                                           problem_max_vals=problem_maximums,
                                           return_blocks=return_blocks)
        return func

    def build_param_list(self, *args: list[np.ndarray])->np.ndarray:
        """
        Takes a list of matrices representing the params to use, which is then turned into a 1D param string as expected by the loss function
        The params have the same order as the functional list
        """
        param_list = []
        for param_chunk in args:
            param_list.append(param_chunk.flatten())
        return np.concatenate(param_list, axis=0)

    def can_make_jac(self):
        return all([hasattr(f, "compute_jac") for f in self.function_blocks])




class abstract_function_block(ABC):
    """
    The abstract function block defines a chain of methods.
    An optimisation function is defined as chains of abstract function blocks.
    This is similar to ceres.

    The class needs to define how to calculate it's index from a line datum
    How does the class optimise for cached variables?
    """

    array_memory: int = 0 #amount of array memory required to compute - default 0, meaning the computation doesn't "need" array mem
    template = False #if the class pulls from a calibration template for some params
    n_inp_read: int | None = None #the number read from a static array: e.g. a perfect calbration target.

    def __init__(self) -> None:
        pass

    @property
    @abstractmethod
    def num_inp(self):
        pass
    num_inp: int #number of differentiable inputs

    @property 
    @abstractmethod
    def num_out(self):
        pass
    num_out: int #number of function return values

    @property
    @abstractmethod
    def params(self): 
        pass
    params: param_type #number of parameters to use.

    @staticmethod
    @abstractmethod
    def compute_fun(params, inp, output, memory: int | np.ndarray = 0):
        pass

    @staticmethod
    @abstractmethod
    def compute_jac(params, inp, output, memory: int | np.ndarray = 0):
        pass

    def __add__(self, other: Type[abstract_function_block]|optimisation_function) -> optimisation_function:
        if issubclass(type(other), abstract_function_block):
            return optimisation_function([self, other])
        if isinstance(other, optimisation_function):
            return optimisation_function([self] + other.function_blocks)
        raise ValueError(f"could not combine function block with {other}")
       

    def __radd__(self, other: Type[abstract_function_block]|optimisation_function) -> optimisation_function:
        if issubclass(type(other), abstract_function_block):
            return optimisation_function([other, self])
        if isinstance(other, optimisation_function):
            return optimisation_function(other.function_blocks + [self])
        raise ValueError(f"could not combine function block with {other}")

    def test_self(self):
        params = np.ones(self.params.n_params)

        outsize = (self.params.n_params + self.num_inp) * self.num_out
        jac_output = np.empty(outsize)

        def fn(params):
            output = np.empty(self.num_out)
            self.compute_fun(
                params[:self.params.n_params],
                params[-self.num_inp:],
                output, 
                memory=np.empty(self.array_memory),
            )
            return output

        self.compute_jac(
            params, 
            np.ones(self.num_inp), 
            jac_output, 
            np.empty((self.array_memory))
        )
        given_jac = jac_output.reshape((self.num_out, -1)) 
        numeric_jac = approx_fprime(np.ones(self.num_inp + self.params.n_params), fn)
        error = given_jac - numeric_jac
        assert np.all(error < 1e-4)

def make_param_struct(
        function_blocks : list[Type[abstract_function_block]], detection_data, max_cams = None, max_imgs = None, max_keys = None,
    ) -> tuple[np.ndarray,np.ndarray, np.ndarray, np.ndarray, int]:
    """
    Takes an input function block definition and detection data, then defines a structure
    for the parameter matrix associated with the input sequence of function blocks.
    Coalesces data into numpy arrays for use in compiled numba code

    :param function_blocks: a list of function blocks that define a loss function
    :param detection_data: the detection data to optimise.
    :returns param_starts: the starting point of each unique set of parameters
    :returns param_offset: the length of each individual parameter string
    :returns param_ids: the id mapping from each function block to the unique params associated.
    :returns param_assoc: the id of the associated parameter in the detection data structure.
    :returns num_inp params: the number of input parameters.
    """
    max_imgs = np.max(detection_data[:, 1]) + 1 if max_imgs is None else max_imgs
    max_keys = np.max(detection_data[:, 2]) + 1 if max_keys is None else max_keys
    max_cams = np.max(detection_data[:, 0]) + 1 if max_cams is None else max_cams
       
 
    param_numbers = {
        key_type.PER_CAM:max_cams,
        key_type.PER_IMG:max_imgs,
        key_type.PER_KEY:max_keys,
    }
    #TODO account for the mod function here, modifying the numbers of params
    unique_link_inds = []
    for fb in function_blocks:
        if not fb.params in unique_link_inds:
            unique_link_inds.append(fb.params)

    block_param_inds = [unique_link_inds.index(fb.params) for fb in function_blocks]
    param_starts = []
    param_offset = []
    associated = []
    starting_point = 0 
    for link_ind in unique_link_inds:
        param_starts.append(starting_point)
        param_offset.append(link_ind.n_params)
        associated.append(int(link_ind.link_type))
        starting_point += link_ind.n_params * param_numbers[link_ind.link_type] 
    
    return np.array(param_starts), np.array(param_offset), np.array(block_param_inds), np.array(associated), int(starting_point)
    
