# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import re
import sys

sys.path.insert(0, os.path.abspath('../..'))

_REPO_ROOT = os.path.abspath('../..')


def _project_version() -> str:
    """The version from pyproject.toml, the one place it is defined.

    tomllib is 3.11+, but nothing else in this build needs a modern
    interpreter -- sphinx-autoapi reads the package statically, so the docs
    build on whatever Python is to hand.  Keep it that way.
    """
    path = os.path.join(_REPO_ROOT, 'pyproject.toml')
    try:
        import tomllib
    except ImportError:
        with open(path, encoding='utf-8') as f:
            return re.search(r'^version\s*=\s*["\'](.+?)["\']', f.read(), re.M).group(1)
    with open(path, 'rb') as f:
        return tomllib.load(f)['project']['version']

# -- Project information -----------------------------------------------------

project = 'pyCamSet'
copyright = '2023-2026, Robin Laven'
author = 'Robin Laven'

# Pinned to the package version so the docs footer cannot drift away from the
# package the docs describe.
release = _project_version()
version = release


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx_copybutton',
    'sphinx.ext.autosectionlabel',
    'autoapi.extension',
    'sphinx.ext.autodoc',
    'sphinx.ext.githubpages'
]

# tells AutoAPI which directories contain the source code to document
autoapi_dirs = ['../../pyCamSet']

# Prefix document path to section labels, otherwise autogenerated labels would
# look like 'heading' rather than 'path/to/file:heading'.
autosectionlabel_prefix_document = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# Only reStructuredText.  A '.md': 'markdown' entry used to be declared here,
# but myst_parser was never in `extensions`, so the first Markdown page added
# to the tree would have failed the build.  Add myst-parser to docs/doq_reqs.txt
# and to `extensions` before reinstating it.
source_suffix = {
    '.rst': 'restructuredtext',
}

numfig = True


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'furo'

html_theme_options = {
    # Puts an "Edit this page" link on every page, pointing at the branch the
    # docs were built from.
    'source_repository': 'https://github.com/rlav440/pyCamSet/',
    'source_branch': 'development',
    'source_directory': 'docs/source/',
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = ['custom.css']

html_logo = '_static/uoa_abi_logo.png'

# Set the root rst to load. This is required to be named contents to allow
# readthedocs to host the docs using its default configuration.
master_doc = 'index'
