from numba import gdb_init
from numba import njit
from pyCamSet.optimisation.abstract_function_blocks import abstract_function_block
from pyCamSet.optimisation.abstract_function_blocks import key_type
from pyCamSet.optimisation.abstract_function_blocks import optimisation_function
from pyCamSet.optimisation.abstract_function_blocks import param_type
from pyCamSet.optimisation.compiled_helpers import n_e4x4_flat_INPLACE
from pyCamSet.optimisation.compiled_helpers import n_htform_prealloc
from pyCamSet.optimisation.compiled_helpers import numba_rodrigues_jac
from time import sleep
import numba
import numpy as np


from numba import prange, int64
from numba.types import int_
import scipy
from datetime import datetime
from pyCamSet.optimisation.abstract_function_blocks import make_param_struct
 
from .matflow_jac_projection_extrinsic3D_template_points import matflow
 
def make_full_jac(op_fun, detections, threads):
    #generated by pyCamSet: sparsity probe seed=0 samples=100. Deterministic -- regenerating must reproduce this file byte for byte.
    @njit(parallel=True,fastmath=True,cache=True)
    def full_jac(inp_params, d_data, block_param_inds, n_lines, inp_mem, out_mem, wrk_mem, param_len, n_threads, d_shape, param_slices, n_outs, f_outs, grad_outputsize, n_params, template = None):
        use_template = template is not None
        t_data: np.ndarray = template if use_template else np.zeros((3,1))
        jac_size = param_slices[-1]
        n_blocks = len(n_params)
        dense_output = np.empty((n_threads, n_lines * f_outs, param_len))
        for i in prange(n_threads):
            #make the memory components required
            inp = np.empty(inp_mem)
            memory = np.empty(wrk_mem)
            dense_param_arr = np.empty(param_len)
            local_params = inp_params[block_param_inds[i].flatten()].reshape((n_lines, param_len))
            output_block = np.empty(69)
            fun_output = np.empty(np.max(n_outs))
            for ii in range(n_lines):
                datum = d_data[i, ii]
                dense_param_arr[:] = local_params[ii]
                if use_template:
                    inp[:3] = t_data[int(datum[2])] 
                ################# BLOCK 2 #################
                params = dense_param_arr[param_slices[2*2]:param_slices[2*2+1]]
                #could set the outputs vector here
                output = output_block[51:69]
                numba_rodrigues_jac(params[:3], memory) #will use 27 points
                output[:18] = 0 
                for op in range(3):
                    for ang_comp in range(3):
                        k = op * 6 + ang_comp
                        output[k] = (
                            memory[9 * ang_comp + op * 3 + 0] * inp[0] + 
                            memory[9 * ang_comp + op * 3 + 1] * inp[1] + 
                            memory[9 * ang_comp + op * 3 + 2] * inp[2]
                        )
                # do the translations 
                output[0 * 6 + 3] = 1
                output[1 * 6 + 4] = 1
                output[2 * 6 + 5] = 1
                ################## normal function eval
                output = fun_output[:n_outs[2]]
                params = dense_param_arr[param_slices[2*2]:param_slices[2*2 + 1]]
                n_e4x4_flat_INPLACE(params, memory[:12])
                n_htform_prealloc(inp, memory[:12], out=output[:3])
                inp[:n_outs[2]] = output[:n_outs[2]]
                ################# BLOCK 1 #################
                params = dense_param_arr[param_slices[2*1]:param_slices[2*1+1]]
                #could set the outputs vector here
                output = output_block[24:51]
                numba_rodrigues_jac(params[:3], memory) #will use 27 points
                output[:] = 0 
                for op in range(3):
                    for ang_comp in range(3):
                        k = op * 9 + ang_comp
                        output[k] = (
                            memory[9 * ang_comp + op * 3 + 0] * inp[0] + 
                            memory[9 * ang_comp + op * 3 + 1] * inp[1] + 
                            memory[9 * ang_comp + op * 3 + 2] * inp[2]
                        )
                # do the translations 
                output[0 * 9 + 3] = 1
                output[1 * 9 + 4] = 1
                output[2 * 9 + 5] = 1
                #do the change with the input variables
                n_e4x4_flat_INPLACE(params, memory[:12])
                for op in range(3):
                    for inval in range(3):
                        k = op*9 + 6 + inval
                        output[k] = memory[inval + 3 * op]
                ################## normal function eval
                output = fun_output[:n_outs[1]]
                params = dense_param_arr[param_slices[2*1]:param_slices[2*1 + 1]]
                n_e4x4_flat_INPLACE(params, memory[:12])
                n_htform_prealloc(inp, memory[:12], out=output[:3])
                inp[:n_outs[1]] = output[:n_outs[1]]
                ################# BLOCK 0 #################
                params = dense_param_arr[param_slices[2*0]:param_slices[2*0+1]]
                #could set the outputs vector here
                output = output_block[0:24]
                """
                The analytic jacobian of the projection, with its subexpressions shared.
                The expanded form of these derivatives repeats (x**2 + y**2) 38 times
                and powers of z 58 times, and numba does not eliminate them, so sharing
                them by hand is ~5x faster. Two groupings do most of the work:
                ``radial``, the distortion polynomial, and ``d_radial``, its derivative
                with respect to r**2.
                """
                f_x, p_x, f_y, p_y = params[0], params[1], params[2], params[3]
                k_0, k_1, p_0, p_1, k_2 = params[4], params[5], params[6], params[7], params[8]
                x, y, z = inp[0], inp[1], inp[2]
                r2 = x*x + y*y
                r4 = r2*r2
                r6 = r4*r2
                z2 = z*z
                z3 = z2*z
                z4 = z2*z2
                z5 = z4*z
                z6 = z3*z3
                z7 = z6*z
                iz2 = 1.0/z2
                iz3 = 1.0/z3
                iz5 = 1.0/z5
                iz7 = 1.0/z7
                iz8 = iz7/z
                radial = k_0*z4*r2 + k_1*z2*r4 + k_2*r6 + z6
                d_radial = k_0*z4 + 2.0*k_1*z2*r2 + 3.0*k_2*r4
                xy = x*y
                xx3 = 3.0*x*x + y*y
                yy3 = x*x + 3.0*y*y
                # dx/dyw and dy/dxw differ only by the focal length
                cross = 2.0*(xy*d_radial + z5*(p_0*x + p_1*y))*iz7
                output[0] = (x*radial + z5*(2.0*p_0*xy + p_1*xx3))*iz7
                output[1] = 1.0
                output[2] = 0.0
                output[3] = 0.0
                output[4] = f_x*x*r2*iz3
                output[5] = f_x*x*r4*iz5
                output[6] = 2.0*f_x*xy*iz2
                output[7] = f_x*xx3*iz2
                output[8] = f_x*x*r6*iz7
                output[9] = f_x*(radial + 2.0*x*x*d_radial + 2.0*z5*(p_0*y + 3.0*p_1*x))*iz7
                output[10] = f_x*cross
                output[11] = -f_x*(4.0*p_0*xy*z5 + 2.0*p_1*z5*xx3
                                   + 2.0*x*r2*d_radial + x*radial)*iz8
                output[12] = 0.0
                output[13] = 0.0
                output[14] = (y*radial + z5*(p_0*yy3 + 2.0*p_1*xy))*iz7
                output[15] = 1.0
                output[16] = f_y*y*r2*iz3
                output[17] = f_y*y*r4*iz5
                output[18] = f_y*yy3*iz2
                output[19] = 2.0*f_y*xy*iz2
                output[20] = f_y*y*r6*iz7
                output[21] = f_y*cross
                output[22] = f_y*(radial + 2.0*y*y*d_radial + 2.0*z5*(3.0*p_0*y + p_1*x))*iz7
                output[23] = -f_y*(2.0*p_0*z5*yy3 + 4.0*p_1*xy*z5
                                   + 2.0*y*r2*d_radial + y*radial)*iz8
                ################## normal function eval
                output = fun_output[:n_outs[0]]
                write_data = dense_output[i, f_outs*ii:f_outs*(ii+1), :]
                matflow(output_block, write_data)
        return dense_output.ravel()
    return full_jac
