from numba import gdb_init
from numba import njit
from pyCamSet.optimisation.abstract_function_blocks import abstract_function_block
from pyCamSet.optimisation.abstract_function_blocks import key_type
from pyCamSet.optimisation.abstract_function_blocks import optimisation_function
from pyCamSet.optimisation.abstract_function_blocks import param_type
from pyCamSet.optimisation.compiled_helpers import n_e4x4_flat_INPLACE
from pyCamSet.optimisation.compiled_helpers import n_htform_prealloc
from pyCamSet.optimisation.compiled_helpers import numba_rodrigues_jac
from time import sleep
import numba
import numpy as np


from numba import prange, int64
from numba.types import int_
import scipy
from datetime import datetime
from pyCamSet.optimisation.abstract_function_blocks import make_param_struct
 
from .matflow_jac_telecentric_intrinsic_telecentric_extrinsic_rigidTform3d_free_point import matflow
 
def make_full_jac(op_fun, detections, threads):
    #generated by pyCamSet: sparsity probe seed=0 samples=100. Deterministic -- regenerating must reproduce this file byte for byte.
    @njit(parallel=True,fastmath=True,cache=True)
    def full_jac(inp_params, d_data, block_param_inds, n_lines, inp_mem, wrk_mem, param_len, n_threads, param_slices, n_outs, f_outs, n_params, template = None):
        use_template = template is not None
        t_data: np.ndarray = template if use_template else np.zeros((3,1))
        n_blocks = len(n_params)
        dense_output = np.empty((n_threads, n_lines * f_outs, param_len))
        for i in prange(n_threads):
            #make the memory components required
            inp = np.empty(inp_mem)
            memory = np.empty(wrk_mem)
            dense_param_arr = np.empty(param_len)
            local_params = inp_params[block_param_inds[i].flatten()].reshape((n_lines, param_len))
            output_block = np.empty(72)
            fun_output = np.empty(np.max(n_outs))
            for ii in range(n_lines):
                datum = d_data[i, ii]
                dense_param_arr[:] = local_params[ii]
                if use_template:
                    inp[:3] = t_data[int(datum[2])] 
                ################# BLOCK 3 #################
                params = dense_param_arr[param_slices[2*3]:param_slices[2*3+1]]
                #could set the outputs vector here
                output = output_block[63:72]
                output[:] = 0
                output[0] = 1
                output[4] = 1
                output[8] = 1
                ################## normal function eval
                output = fun_output[:n_outs[3]]
                params = dense_param_arr[param_slices[2*3]:param_slices[2*3 + 1]]
                output[0] = params[0]
                output[1] = params[1]
                output[2] = params[2]
                inp[:n_outs[3]] = output[:n_outs[3]]
                ################# BLOCK 2 #################
                params = dense_param_arr[param_slices[2*2]:param_slices[2*2+1]]
                #could set the outputs vector here
                output = output_block[36:63]
                numba_rodrigues_jac(params[:3], memory) #will use 27 points
                output[:] = 0 
                for op in range(3):
                    for ang_comp in range(3):
                        k = op * 9 + ang_comp
                        output[k] = (
                            memory[9 * ang_comp + op * 3 + 0] * inp[0] + 
                            memory[9 * ang_comp + op * 3 + 1] * inp[1] + 
                            memory[9 * ang_comp + op * 3 + 2] * inp[2]
                        )
                # do the translations 
                output[0 * 9 + 3] = 1
                output[1 * 9 + 4] = 1
                output[2 * 9 + 5] = 1
                #do the change with the input variables
                n_e4x4_flat_INPLACE(params, memory[:12])
                for op in range(3):
                    for inval in range(3):
                        k = op*9 + 6 + inval
                        output[k] = memory[inval + 3 * op]
                ################## normal function eval
                output = fun_output[:n_outs[2]]
                params = dense_param_arr[param_slices[2*2]:param_slices[2*2 + 1]]
                n_e4x4_flat_INPLACE(params, memory[:12])
                n_htform_prealloc(inp, memory[:12], out=output[:3])
                inp[:n_outs[2]] = output[:n_outs[2]]
                ################# BLOCK 1 #################
                params = dense_param_arr[param_slices[2*1]:param_slices[2*1+1]]
                #could set the outputs vector here
                output = output_block[18:36]
                numba_rodrigues_jac(params[:3], memory)  # uses all 27
                output[:18] = 0
                for op in range(3):
                    for ang_comp in range(3):
                        k = op * 6 + ang_comp
                        output[k] = (
                            memory[9 * ang_comp + op * 3 + 0] * inp[0] +
                            memory[9 * ang_comp + op * 3 + 1] * inp[1] +
                            memory[9 * ang_comp + op * 3 + 2] * inp[2]
                        )
                # every rodrigues value has been read, so the scratch is free again
                memory[12] = params[0]
                memory[13] = params[1]
                memory[14] = params[2]
                memory[15] = 0.0
                memory[16] = 0.0
                memory[17] = 0.0
                n_e4x4_flat_INPLACE(memory[12:18], memory[:12])
                for op in range(3):
                    for inval in range(3):
                        k = op * 6 + 3 + inval
                        output[k] = memory[inval + 3 * op]
                ################## normal function eval
                output = fun_output[:n_outs[1]]
                params = dense_param_arr[param_slices[2*1]:param_slices[2*1 + 1]]
                memory[12] = params[0]
                memory[13] = params[1]
                memory[14] = params[2]
                memory[15] = 0.0
                memory[16] = 0.0
                memory[17] = 0.0
                n_e4x4_flat_INPLACE(memory[12:18], memory[:12])
                n_htform_prealloc(inp, memory[:12], out=output[:3])
                inp[:n_outs[1]] = output[:n_outs[1]]
                ################# BLOCK 0 #################
                params = dense_param_arr[param_slices[2*0]:param_slices[2*0+1]]
                #could set the outputs vector here
                output = output_block[0:18]
                """
                The analytic jacobian of the telecentric projection, subexpressions shared.
                Both rows are built from the same five groupings: ``den``, the division
                model; ``d2``, its derivative with respect to the squared radius;
                ``A``, which every depth-like derivative carries; and ``Bx``/``By``,
                which carry the two in-plane ones.  ``eps`` and ``z`` differ only by a
                factor, since both enter solely through ``w``.
                """
                m_x, c_x, m_y, c_y = params[0], params[1], params[2], params[3]
                k, eps = params[4], params[5]
                x, y, z = inp[0], inp[1], inp[2]
                w = 1.0/(1.0 + eps*z)
                xs = m_x*x*w
                ys = m_y*y*w
                q = xs*xs + ys*ys
                r2 = q*1e-6
                den = 1.0/(1.0 + k*r2)
                d2 = -k*1e-6*den*den
                A = den + 2.0*d2*q
                Bx = den + 2.0*d2*xs*xs
                By = den + 2.0*d2*ys*ys
                cr = 2.0*d2*xs*ys
                dk = -r2*den*den
                output[0] = x*w*Bx
                output[1] = 1.0
                output[2] = cr*y*w
                output[3] = 0.0
                output[4] = xs*dk
                output[5] = -z*w*xs*A
                output[6] = m_x*w*Bx
                output[7] = cr*m_y*w
                output[8] = -eps*w*xs*A
                output[9] = cr*x*w
                output[10] = 0.0
                output[11] = y*w*By
                output[12] = 1.0
                output[13] = ys*dk
                output[14] = -z*w*ys*A
                output[15] = cr*m_x*w
                output[16] = m_y*w*By
                output[17] = -eps*w*ys*A
                ################## normal function eval
                output = fun_output[:n_outs[0]]
                write_data = dense_output[i, f_outs*ii:f_outs*(ii+1), :]
                matflow(output_block, write_data)
        return dense_output.ravel()
    return full_jac
