from numba import gdb_init
from numba import njit
from pyCamSet.optimisation.abstract_function_blocks import abstract_function_block
from pyCamSet.optimisation.abstract_function_blocks import key_type
from pyCamSet.optimisation.abstract_function_blocks import optimisation_function
from pyCamSet.optimisation.abstract_function_blocks import param_type
from pyCamSet.optimisation.compiled_helpers import n_e4x4_flat_INPLACE
from pyCamSet.optimisation.compiled_helpers import n_htform_prealloc
from pyCamSet.optimisation.compiled_helpers import numba_rodrigues_jac
from time import sleep
import numba
import numpy as np


from numba import prange, int64
from datetime import datetime
from pyCamSet.optimisation.abstract_function_blocks import make_param_struct
 
def make_full_loss(op_fun, detections, threads):
    op_fun._prep_for_computation()
    #generated by pyCamSet: sparsity probe seed=0 samples=100. Deterministic -- regenerating must reproduce this file byte for byte.
    @njit(parallel=True, fastmath=True, cache=True)
    def full_loss(inp_params, d_data, block_param_inds, n_lines, inp_mem, out_mem, wrk_mem, param_len, n_threads, d_shape, param_slices, n_outs, template = None):
        use_template = template is not None
        t_data: np.ndarray = template if use_template else np.zeros((3,1))
        losses = np.empty((n_threads, n_lines, 2))
        for i in prange(n_threads):
            #make the memory components required
            inp = np.empty(inp_mem)
            output = np.empty(out_mem)
            memory = np.empty(wrk_mem)
            dense_param_arr = np.empty(param_len)
            local_params = inp_params[block_param_inds[i].flatten()].reshape((int64(n_lines), int64(param_len)))
            for ii in range(n_lines):
                datum = d_data[i, ii]
                dense_param_arr[:] = local_params[ii]
                if use_template:
                    inp[:3] = t_data[int(datum[2])] 
                params = dense_param_arr[param_slices[2*2]:param_slices[2*2 + 1]]
                output[0] = params[0]
                output[1] = params[1]
                output[2] = params[2]
                inp[:n_outs[2]] = output[:n_outs[2]]
                params = dense_param_arr[param_slices[2*1]:param_slices[2*1 + 1]]
                n_e4x4_flat_INPLACE(params, memory[:12])
                n_htform_prealloc(inp, memory[:12], out=output[:3])
                inp[:n_outs[1]] = output[:n_outs[1]]
                params = dense_param_arr[param_slices[2*0]:param_slices[2*0 + 1]]
                """
                Projects a camera frame point to pixels through the 5 term distortion.
                The previous form scaled by the focal length and principal point and
                then immediately undid it (``x = (u - p_x)/f_x`` recovers ``x/z``), and
                recomputed r**2 and its powers throughout; going straight to normalised
                coordinates and sharing the powers is ~3.4x faster and slightly more
                accurate.
                """
                f_x, p_x, f_y, p_y = params[0], params[1], params[2], params[3]
                k_0, k_1, p_0, p_1, k_2 = params[4], params[5], params[6], params[7], params[8]
                inv_z = 1.0/inp[2]
                x = inp[0] * inv_z
                y = inp[1] * inv_z
                r2 = x*x + y*y
                r4 = r2*r2
                kup = 1.0 + k_0*r2 + k_1*r4 + k_2*r4*r2
                xy = x*y
                xD = x*kup + 2.0*p_0*xy + p_1*(r2 + 2.0*x*x)
                yD = y*kup + p_0*(r2 + 2.0*y*y) + 2.0*p_1*xy
                output[0] = xD*f_x + p_x
                output[1] = yD*f_y + p_y
                inp[:n_outs[0]] = output[:n_outs[0]]
                losses[i, ii] = [output[0] - datum[3], output[1] - datum[4]]
        return np.resize(losses, (d_shape, 2))
    return full_loss