from numba import gdb_init
from numba import njit
from pyCamSet.optimisation.abstract_function_blocks import abstract_function_block
from pyCamSet.optimisation.abstract_function_blocks import key_type
from pyCamSet.optimisation.abstract_function_blocks import optimisation_function
from pyCamSet.optimisation.abstract_function_blocks import param_type
from pyCamSet.optimisation.compiled_helpers import n_e4x4_flat_INPLACE
from pyCamSet.optimisation.compiled_helpers import n_htform_prealloc
from pyCamSet.optimisation.compiled_helpers import numba_rodrigues_jac
from time import sleep
import numba
import numpy as np


from numba import prange, int64
from datetime import datetime
from pyCamSet.optimisation.abstract_function_blocks import make_param_struct
 
def make_full_loss(op_fun, detections, threads):
    op_fun._prep_for_computation()
    #generated by pyCamSet: sparsity probe seed=0 samples=100. Deterministic -- regenerating must reproduce this file byte for byte.
    @njit(parallel=True, fastmath=True, cache=True)
    def full_loss(inp_params, d_data, block_param_inds, n_lines, inp_mem, out_mem, wrk_mem, param_len, n_threads, d_shape, param_slices, n_outs, template = None):
        use_template = template is not None
        t_data: np.ndarray = template if use_template else np.zeros((3,1))
        losses = np.empty((n_threads, n_lines, 2))
        for i in prange(n_threads):
            #make the memory components required
            inp = np.empty(inp_mem)
            output = np.empty(out_mem)
            memory = np.empty(wrk_mem)
            dense_param_arr = np.empty(param_len)
            local_params = inp_params[block_param_inds[i].flatten()].reshape((int64(n_lines), int64(param_len)))
            for ii in range(n_lines):
                datum = d_data[i, ii]
                dense_param_arr[:] = local_params[ii]
                if use_template:
                    inp[:3] = t_data[int(datum[2])] 
                params = dense_param_arr[param_slices[2*2]:param_slices[2*2 + 1]]
                n_e4x4_flat_INPLACE(params, memory[:12])
                n_htform_prealloc(inp, memory[:12], out=output[:3])
                inp[:n_outs[2]] = output[:n_outs[2]]
                params = dense_param_arr[param_slices[2*1]:param_slices[2*1 + 1]]
                memory[12] = params[0]
                memory[13] = params[1]
                memory[14] = params[2]
                memory[15] = 0.0
                memory[16] = 0.0
                memory[17] = 0.0
                n_e4x4_flat_INPLACE(memory[12:18], memory[:12])
                n_htform_prealloc(inp, memory[:12], out=output[:3])
                inp[:n_outs[1]] = output[:n_outs[1]]
                params = dense_param_arr[param_slices[2*0]:param_slices[2*0 + 1]]
                m_x, c_x, m_y, c_y = params[0], params[1], params[2], params[3]
                k, eps = params[4], params[5]
                w = 1.0/(1.0 + eps*inp[2])
                xs = m_x*inp[0]*w
                ys = m_y*inp[1]*w
                r2 = (xs*xs + ys*ys)*1e-6
                den = 1.0/(1.0 + k*r2)
                output[0] = xs*den + c_x
                output[1] = ys*den + c_y
                inp[:n_outs[0]] = output[:n_outs[0]]
                losses[i, ii] = [output[0] - datum[3], output[1] - datum[4]]
        return np.resize(losses, (d_shape, 2))
    return full_loss