"""Regenerate requirements-core.txt from pyproject.toml.

The GUI is the default install, so PySide6 is a base dependency -- and at
1.2 GB it is larger than everything else combined.  A lean install therefore
cannot be an extra (extras only ever add packages); it is
``pip install pyCamSet --no-deps`` plus the file this script writes.

Run it after changing ``[project] dependencies``.  test_core_requirements.py
fails if the file is stale, so CI catches a forgotten run.
"""
from __future__ import annotations

import tomllib
from pathlib import Path

#: Base dependencies the lean install leaves out.
EXCLUDED = {"PySide6"}

HEADER = """\
# Generated by setup_scripts/write_core_requirements.py -- do not edit.
#
# The dependencies of a lean pyCamSet install: everything in pyproject.toml's
# [project] dependencies except the GUI toolkit.  Plotting still works; only
# the Qt GUI and the `pycamset` command are unavailable.
#
#     pip install pyCamSet --no-deps
#     pip install -r requirements-core.txt
"""

ROOT = Path(__file__).resolve().parent.parent


def core_requirements() -> list[str]:
    """Return the base dependencies with the GUI toolkit removed."""
    data = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    return [
        dep for dep in data["project"]["dependencies"]
        # match on the distribution name, before any version specifier
        if dep.split(">")[0].split("<")[0].split("=")[0].split("[")[0].strip()
        not in EXCLUDED
    ]


def rendered() -> str:
    """Return the full text the file should contain."""
    return HEADER + "\n".join(core_requirements()) + "\n"


if __name__ == "__main__":
    target = ROOT / "requirements-core.txt"
    target.write_text(rendered(), encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)} ({len(core_requirements())} requirements)")
